version: '3'
services:
  # Railsの設定
  web:
    # build: .でdocker-compose.ymlと同じフォルダにDockerfileがあることを示す
    build: .
    # 事前に手元で/tmp/pids/server.pidを削除する
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Portfolio:delegated
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - chrome
  # Postgresの設定
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5433:5432
    volumes:
      - Postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
      TZ: "Asia/Tokyo"
  #Chromeの設定
  chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: 512m
    ports:
      - 4444:4444
volumes:
  Postgres-data:
  bundle_data:
  node_modules: